const products = [
    {
        title: "Chocolate Cake",
        frosting: "Chocolate",
        addOns: "Chocolate Syrup, Sprinkles",
        image: 'images/cake1.jpg',
        price: 250,
    },
    {
        title: "Cupcake",
        frosting: "Strawberry",
        addOns: "Vanilla Syrup, Strawberry",
        image: 'images/cake2.jpg',
        price: 300,
    },
    {
        title: "Ice Cream Cake",
        frosting: "Chocolate",
        addOns: "Chocolate Syrup",
        image: 'images/cake3.jpg',
        price: 350,
    },
    {
        title: "Fruit Cake",
        frosting: "Vanilla",
        addOns: "Fruits",
        image: 'images/cake4.jpg',
        price: 250,
        
    },
    {
        title: "Cake",
        frosting: "Vanilla",
        addOns: "Fruits, Blueberry",
        image: 'images/cake5.jpg',
        price: 250, 
    },
    {
        title: "Chocolate Cake",
        frosting: "Chocolate",
        addOns: "Blueberry, Strawberry",
        image: 'images/cake6.jpg',
        price: 300,
    },
    {
        title: "Donuts",
        frosting: "Chocolate",
        addOns: "Vanilla Syrup,Chocolate Syrup, Sprinkles",
        image: 'images/cake7.jpg',
        price: 300,
    },
    {
        title: "Cake",
        frosting: "Vanilla",
        addOns: "Chocolate Syrup, Strawberry",
        image: 'images/cake8.jpg',
        price: 300,
    },
    {
        title: "Cupcake",
        frosting: "Strawberry",
        addOns: "Vanilla Syrup, Strawberry",
        image: 'images/cake9.jpg',
        price: 300,
    },
    {
        title: "Cupcake",
        frosting: "Vanilla",
        addOns: "Chocolate, Marshmallow",
        image: 'images/cake10.jpg',
        price: 300,
    },
    {
        title: "Cupcake",
        frosting: "Strawberry",
        addOns: "Blueberry, Strawberry",
        image: 'images/cake11.jpg',
        price: 300,
    },
    {
        title: "Cake",
        frosting: "Vanilla",
        addOns: "Strawberry",
        image: 'images/cake12.jpg',
        price: 300,
    },
    {
        title: "Cheese Cake",
        image: 'images/cake13.jpg',
        price: 300,
    },
    {
        title: "Strawberry Cake",
        frosting: "Vanilla",
        addOns: "Chocolate",
        image: 'images/cake13.jpg',
        price: 300,
    },
    {
        title: "Strawberry Cake",
        frosting: "Vanilla",
        addOns: "Chocolate",
        image: 'images/cake13.jpg',
        price: 300,
    },
    

];
